In [48]:
import pandas as pd
import numpy as np

In [49]:
import os
os.chdir("/workspaces/group-project-team2/checkpoint/data_acquisition/")

## Data Import
Loading the BRFSS (Behavioral Risk Factor Surveillance System) 2024 dataset from a SAS file format (.XPT). This dataset contains health-related survey data.

In [50]:
brfss1 = pd.read_parquet("BRFSS_2024_1.parquet.gzip")
brfss2 =  pd.read_parquet("BRFSS_2024_2.parquet.gzip")

## Initial Data Inspection and Merging
Displaying basic information about the dataset including:
- Number of rows and columns
- Data types of each column
- Memory usage
- Non-null counts

In [51]:
brfss1.info()
brfss2.info()

<class 'pandas.DataFrame'>
RangeIndex: 228835 entries, 0 to 228834
Columns: 301 entries, _STATE to _AIDTST4
dtypes: float64(296), object(5)
memory usage: 525.5+ MB
<class 'pandas.DataFrame'>
RangeIndex: 228835 entries, 228835 to 457669
Columns: 301 entries, _STATE to _AIDTST4
dtypes: float64(296), object(5)
memory usage: 525.5+ MB

In [52]:
brfss = pd.concat([brfss1, brfss2], axis = 0)

In [53]:
brfss.info()

<class 'pandas.DataFrame'>
RangeIndex: 457670 entries, 0 to 457669
Columns: 301 entries, _STATE to _AIDTST4
dtypes: float64(296), object(5)
memory usage: 1.0+ GB

## Dataset Overview
Displaying statistical summary of the dataset:
- Count of non-null values
- Mean, standard deviation
- Minimum, maximum values
- Quartile distributions (25%, 50%, 75%)

In [54]:
brfss.describe()

,_STATE,FMONTH,DISPCODE,_PSU,CTELENM1,PVTRESD1,COLGHOUS,STATERE1,CELPHON1,LADULT1,...,_LCSCTSN,_LCSPSTF,DRNKANY6,DROCDY4_,_RFBING6,_DRNKWK3,_RFDRHV9,_FLSHOT7,_PNEUMO3,_AIDTST4
count,457670.000000,457670.000000,457670.000000,4.576700e+05,81730.0,81730.000000,14.0,81730.0,81730.0,81730.000000,...,393433.000000,406226.000000,457670.000000,4.576690e+05,457670.000000,4.576700e+05,457670.000000,179344.000000,179344.000000,414178.000000
mean,30.823537,6.426995,1118.669784,2.024007e+09,1.0,1.000171,1.0,1.0,2.0,1.001835,...,3.420252,8.468687,2.196764,1.000599e+02,1.948965,1.044393e+04,1.869063,2.336850,2.462223,1.999684
std,15.939364,3.356938,38.966920,7.488291e+03,0.0,0.013087,0.0,0.0,0.0,0.042801,...,0.792956,1.892208,2.226566,2.613717e+02,2.418721,3.016653e+04,2.414067,2.602255,2.814818,1.665037
min,1.000000,1.000000,1100.000000,2.024000e+09,1.0,1.000000,1.0,1.0,2.0,1.000000,...,1.000000,1.000000,1.000000,5.397605e-79,1.000000,5.397605e-79,1.000000,1.000000,1.000000,1.000000
25%,18.000000,4.000000,1100.000000,2.024002e+09,1.0,1.000000,1.0,1.0,2.0,1.000000,...,3.000000,9.000000,1.000000,5.397605e-79,1.000000,5.397605e-79,1.000000,1.000000,1.000000,1.000000
50%,31.000000,7.000000,1100.000000,2.024005e+09,1.0,1.000000,1.0,1.0,2.0,1.000000,...,4.000000,9.000000,2.000000,3.000000e+00,1.000000,4.700000e+01,1.000000,1.000000,1.000000,2.000000
75%,44.000000,9.000000,1100.000000,2.024008e+09,1.0,1.000000,1.0,1.0,2.0,1.000000,...,4.000000,9.000000,2.000000,2.900000e+01,1.000000,4.670000e+02,1.000000,2.000000,2.000000,2.000000
max,78.000000,12.000000,1200.000000,2.024044e+09,1.0,2.000000,1.0,1.0,2.0,2.000000,...,4.000000,9.000000,9.000000,9.000000e+02,9.000000,9.990000e+04,9.000000,9.000000,9.000000,9.000000

In [55]:
brfss.head()

,_STATE,FMONTH,IDATE,IMONTH,IDAY,IYEAR,DISPCODE,SEQNO,_PSU,CTELENM1,...,_LCSCTSN,_LCSPSTF,DRNKANY6,DROCDY4_,_RFBING6,_DRNKWK3,_RFDRHV9,_FLSHOT7,_PNEUMO3,_AIDTST4
0,1.0,2.0,b'02282024',b'02',b'28',b'2024',1100.0,b'2024000001',2.024000e+09,1.0,...,NaN,9.0,2.0,5.397605e-79,1.0,5.397605e-79,1.0,1.0,2.0,2.0
1,1.0,2.0,b'02212024',b'02',b'21',b'2024',1100.0,b'2024000002',2.024000e+09,1.0,...,4.0,9.0,2.0,5.397605e-79,1.0,5.397605e-79,1.0,1.0,1.0,2.0
2,1.0,2.0,b'02212024',b'02',b'21',b'2024',1100.0,b'2024000003',2.024000e+09,1.0,...,4.0,2.0,1.0,1.000000e+02,2.0,1.400000e+03,1.0,NaN,NaN,2.0
3,1.0,2.0,b'02282024',b'02',b'28',b'2024',1100.0,b'2024000004',2.024000e+09,1.0,...,NaN,9.0,2.0,5.397605e-79,1.0,5.397605e-79,1.0,1.0,1.0,2.0
4,1.0,2.0,b'02212024',b'02',b'21',b'2024',1100.0,b'2024000005',2.024000e+09,1.0,...,3.0,9.0,2.0,5.397605e-79,1.0,5.397605e-79,1.0,NaN,NaN,2.0

## Column Names Inspection
Displaying all column names in the dataset to identify available features for analysis.

In [56]:
for col in brfss.columns:
    print(col)

_STATE
FMONTH
IDATE
IMONTH
IDAY
IYEAR
DISPCODE
SEQNO
_PSU
CTELENM1
PVTRESD1
COLGHOUS
STATERE1
CELPHON1
LADULT1
NUMADULT
RESPSLC1
LANDSEX3
SAFETIME
CTELNUM1
CELLFON5
CADULT1
CELLSEX3
PVTRESD3
CCLGHOUS
CSTATE1
LANDLINE
HHADULT
SEXVAR
GENHLTH
PHYSHLTH
MENTHLTH
POORHLTH
PRIMINS2
PERSDOC3
MEDCOST1
CHECKUP1
EXERANY2
LASTDEN4
RMVTETH4
CVDINFR4
CVDCRHD4
CVDSTRK3
ASTHMA3
ASTHNOW
CHCSCNC1
CHCOCNC1
CHCCOPD3
ADDEPEV3
CHCKDNY2
HAVARTH4
DIABETE4
DIABAGE4
MARITAL
EDUCA
RENTHOM1
NUMHHOL4
NUMPHON4
CPDEMO1C
VETERAN3
EMPLOY1
CHILDREN
INCOME3
PREGNANT
WEIGHT2
HEIGHT3
DEAF
BLIND
DECIDE
DIFFWALK
DIFFDRES
DIFFALON
HADMAM
HOWLONG
CERVSCRN
CRVCLCNC
CRVCLPAP
CRVCLHPV
HADHYST2
HADSIGM4
COLNSIGM
COLNTES1
SIGMTES1
LASTSIG4
COLNCNCR
VIRCOLO1
VCLNTES2
SMALSTOL
STOLTEST
STOOLDN2
BLDSTFIT
SDNATES1
SMOKE100
SMOKDAY2
USENOW3
ECIGNOW3
LCSFIRST
LCSNUMCG
LCSCTSC1
LCSSCNCR
LCSCTWHN
ALCDAY4
AVEDRNK4
DRNK3GE5
MAXDRNKS
FLUSHOT7
FLSHTMY3
IMFVPLA5
PNEUVAC4
HIVTST7
HIVTSTD3
HIVRISK5
PDIABTS1
PREDIAB2
DIABTYPE
INSULIN1
CHKHEMO3
EYEEXAM1
DIABEYE1
DIABEDU1
FEETSORE
ARTHEXER
SHINGLE2
HPVADVC4
HPVADSH1
TETANUS1
CNCRDIFF
CNCRAGE
CNCRTYP2
CSRVTRT3
CSRVDOC1
CSRVSUM
CSRVRTRN
CSRVINST
CSRVINSR
CSRVDEIN
CSRVCLIN
CSRVPAIN
CSRVCTL2
PSATEST1
PSATIME1
PCPSARS2
PSASUGS1
PCSTALK2
CIMEMLO1
CDWORRY
CDDISCU1
CDHOUS1
CDSOCIA1
CAREGIV1
CRGVREL5
CRGVPRB4
CRGVALZD
CRGVNURS
CRGVPER2
CRGVHOU2
CRGVHRS2
CRGVLNG2
ACEDEPRS
ACEDRINK
ACEDRUGS
ACEPRISN
ACEDIVRC
ACEPUNCH
ACEHURT1
ACESWEAR
ACETOUCH
ACETTHEM
ACEHVSEX
ACEADSAF
ACEADNED
LSATISFY
EMTSUPRT
SDLONELY
SDHEMPLY
FOODSTMP
SDHFOOD1
SDHBILLS
SDHUTILS
SDHTRNSP
HOWSAFE1
MARIJAN1
MARJSMOK
MARJEAT
MARJVAPE
MARJDAB
MARJOTHR
USEMRJN4
LASTSMK2
STOPSMK2
MENTCIGS
MENTECIG
HEATTBCO
SSBSUGR2
SSBFRUT3
FIREARM5
GUNLOAD
LOADULK2
RCSGEND1
RCSXBRTH
RCSRLTN2
CASTHDX2
CASTHNO2
SOMALE
SOFEMALE
HADSEX
PFPPRVN4
TYPCNTR9
NOBCUSE8
QSTVER
QSTLANG
HPVDSHT
ICFQSTVR
_METSTAT
_URBSTAT
MSCODE
_STSTR
_STRWT
_RAWRAKE
_WT2RAKE
_IMPRACE
_CHISPNC
_CRACE1
CAGEG
_CLLCPWT
_DUALUSE
_DUALCOR
_LLCPWT2
_LLCPWT
_RFHLTH
_PHYS14D
_MENT14D
_HLTHPL2
_HCVU654
_TOTINDA
_EXTETH3
_ALTETH3
_DENVST3
_MICHD
_LTASTH1
_CASTHM1
_ASTHMS1
_DRDXAR2
_MRACE1
_HISPANC
_RACE
_RACEG21
_RACEGR3
_RACEPRV
_SEX
_AGEG5YR
_AGE65YR
_AGE80
_AGE_G
HTIN4
HTM4
WTKG3
_BMI5
_BMI5CAT
_RFBMI5
_CHLDCNT
_EDUCAG
_INCOMG1
_RFMAM23
_MAM402Y
_CRVSCRN
_RFPAP37
_HPV5YR1
_PAPHPV1
_HADCOLN
_CLNSCP2
_HADSIGM
_SGMSCP2
_SGMS102
_RFBLDS6
_STOLDN2
_VIRCOL2
_SBONTI2
_CRCREC3
_SMOKER3
_RFSMOK3
_CURECI3
LCSLAST_
LCSNUMC_
_LCSAGE
_LCSYSMK
_PACKDAY
_PACKYRS
_LCSYQTS
_LCSSMKG
_LCSELIG
_LCSCTSN
_LCSPSTF
DRNKANY6
DROCDY4_
_RFBING6
_DRNKWK3
_RFDRHV9
_FLSHOT7
_PNEUMO3
_AIDTST4

In [57]:
columns_list = brfss.columns.tolist()
print(columns_list)

['_STATE', 'FMONTH', 'IDATE', 'IMONTH', 'IDAY', 'IYEAR', 'DISPCODE', 'SEQNO', '_PSU', 'CTELENM1', 'PVTRESD1', 'COLGHOUS', 'STATERE1', 'CELPHON1', 'LADULT1', 'NUMADULT', 'RESPSLC1', 'LANDSEX3', 'SAFETIME', 'CTELNUM1', 'CELLFON5', 'CADULT1', 'CELLSEX3', 'PVTRESD3', 'CCLGHOUS', 'CSTATE1', 'LANDLINE', 'HHADULT', 'SEXVAR', 'GENHLTH', 'PHYSHLTH', 'MENTHLTH', 'POORHLTH', 'PRIMINS2', 'PERSDOC3', 'MEDCOST1', 'CHECKUP1', 'EXERANY2', 'LASTDEN4', 'RMVTETH4', 'CVDINFR4', 'CVDCRHD4', 'CVDSTRK3', 'ASTHMA3', 'ASTHNOW', 'CHCSCNC1', 'CHCOCNC1', 'CHCCOPD3', 'ADDEPEV3', 'CHCKDNY2', 'HAVARTH4', 'DIABETE4', 'DIABAGE4', 'MARITAL', 'EDUCA', 'RENTHOM1', 'NUMHHOL4', 'NUMPHON4', 'CPDEMO1C', 'VETERAN3', 'EMPLOY1', 'CHILDREN', 'INCOME3', 'PREGNANT', 'WEIGHT2', 'HEIGHT3', 'DEAF', 'BLIND', 'DECIDE', 'DIFFWALK', 'DIFFDRES', 'DIFFALON', 'HADMAM', 'HOWLONG', 'CERVSCRN', 'CRVCLCNC', 'CRVCLPAP', 'CRVCLHPV', 'HADHYST2', 'HADSIGM4', 'COLNSIGM', 'COLNTES1', 'SIGMTES1', 'LASTSIG4', 'COLNCNCR', 'VIRCOLO1', 'VCLNTES2', 'SMALSTOL', 'STOLTEST', 'STOOLDN2', 'BLDSTFIT', 'SDNATES1', 'SMOKE100', 'SMOKDAY2', 'USENOW3', 'ECIGNOW3', 'LCSFIRST', 'LCSNUMCG', 'LCSCTSC1', 'LCSSCNCR', 'LCSCTWHN', 'ALCDAY4', 'AVEDRNK4', 'DRNK3GE5', 'MAXDRNKS', 'FLUSHOT7', 'FLSHTMY3', 'IMFVPLA5', 'PNEUVAC4', 'HIVTST7', 'HIVTSTD3', 'HIVRISK5', 'PDIABTS1', 'PREDIAB2', 'DIABTYPE', 'INSULIN1', 'CHKHEMO3', 'EYEEXAM1', 'DIABEYE1', 'DIABEDU1', 'FEETSORE', 'ARTHEXER', 'SHINGLE2', 'HPVADVC4', 'HPVADSH1', 'TETANUS1', 'CNCRDIFF', 'CNCRAGE', 'CNCRTYP2', 'CSRVTRT3', 'CSRVDOC1', 'CSRVSUM', 'CSRVRTRN', 'CSRVINST', 'CSRVINSR', 'CSRVDEIN', 'CSRVCLIN', 'CSRVPAIN', 'CSRVCTL2', 'PSATEST1', 'PSATIME1', 'PCPSARS2', 'PSASUGS1', 'PCSTALK2', 'CIMEMLO1', 'CDWORRY', 'CDDISCU1', 'CDHOUS1', 'CDSOCIA1', 'CAREGIV1', 'CRGVREL5', 'CRGVPRB4', 'CRGVALZD', 'CRGVNURS', 'CRGVPER2', 'CRGVHOU2', 'CRGVHRS2', 'CRGVLNG2', 'ACEDEPRS', 'ACEDRINK', 'ACEDRUGS', 'ACEPRISN', 'ACEDIVRC', 'ACEPUNCH', 'ACEHURT1', 'ACESWEAR', 'ACETOUCH', 'ACETTHEM', 'ACEHVSEX', 'ACEADSAF', 'ACEADNED', 'LSATISFY', 'EMTSUPRT', 'SDLONELY', 'SDHEMPLY', 'FOODSTMP', 'SDHFOOD1', 'SDHBILLS', 'SDHUTILS', 'SDHTRNSP', 'HOWSAFE1', 'MARIJAN1', 'MARJSMOK', 'MARJEAT', 'MARJVAPE', 'MARJDAB', 'MARJOTHR', 'USEMRJN4', 'LASTSMK2', 'STOPSMK2', 'MENTCIGS', 'MENTECIG', 'HEATTBCO', 'SSBSUGR2', 'SSBFRUT3', 'FIREARM5', 'GUNLOAD', 'LOADULK2', 'RCSGEND1', 'RCSXBRTH', 'RCSRLTN2', 'CASTHDX2', 'CASTHNO2', 'SOMALE', 'SOFEMALE', 'HADSEX', 'PFPPRVN4', 'TYPCNTR9', 'NOBCUSE8', 'QSTVER', 'QSTLANG', 'HPVDSHT', 'ICFQSTVR', '_METSTAT', '_URBSTAT', 'MSCODE', '_STSTR', '_STRWT', '_RAWRAKE', '_WT2RAKE', '_IMPRACE', '_CHISPNC', '_CRACE1', 'CAGEG', '_CLLCPWT', '_DUALUSE', '_DUALCOR', '_LLCPWT2', '_LLCPWT', '_RFHLTH', '_PHYS14D', '_MENT14D', '_HLTHPL2', '_HCVU654', '_TOTINDA', '_EXTETH3', '_ALTETH3', '_DENVST3', '_MICHD', '_LTASTH1', '_CASTHM1', '_ASTHMS1', '_DRDXAR2', '_MRACE1', '_HISPANC', '_RACE', '_RACEG21', '_RACEGR3', '_RACEPRV', '_SEX', '_AGEG5YR', '_AGE65YR', '_AGE80', '_AGE_G', 'HTIN4', 'HTM4', 'WTKG3', '_BMI5', '_BMI5CAT', '_RFBMI5', '_CHLDCNT', '_EDUCAG', '_INCOMG1', '_RFMAM23', '_MAM402Y', '_CRVSCRN', '_RFPAP37', '_HPV5YR1', '_PAPHPV1', '_HADCOLN', '_CLNSCP2', '_HADSIGM', '_SGMSCP2', '_SGMS102', '_RFBLDS6', '_STOLDN2', '_VIRCOL2', '_SBONTI2', '_CRCREC3', '_SMOKER3', '_RFSMOK3', '_CURECI3', 'LCSLAST_', 'LCSNUMC_', '_LCSAGE', '_LCSYSMK', '_PACKDAY', '_PACKYRS', '_LCSYQTS', '_LCSSMKG', '_LCSELIG', '_LCSCTSN', '_LCSPSTF', 'DRNKANY6', 'DROCDY4_', '_RFBING6', '_DRNKWK3', '_RFDRHV9', '_FLSHOT7', '_PNEUMO3', '_AIDTST4']

## Selecting Relevant Features


- **_AGE_G (Age Group)**: Essential demographic variable that allows for age-stratified analysis and controls for age-related health patterns in outcome assessment.

- **_SEX (Sex)**: Key demographic predictor as health outcomes and risk factors often differ significantly between males and females.

- **_BMI5 (Body Mass Index)**: Direct quantitative measure of body weight relative to height, crucial for assessing weight-related health risks.

- **_RFBMI5 (Obese)**: Binary obesity classification derived from BMI, serving as a primary outcome variable for identifying obesity prevalence and risk factors.

- **HTM4 (Height)**: Anthropometric measure needed for BMI calculations and body composition assessments.

- **_TOTINDA (Physical Activity)**: Important behavioral variable; physical activity is a known protective factor against obesity and chronic diseases.

- **WTKG3 (Weight)**: Direct weight measurement in kilograms, essential for BMI computation and weight status classification.

- **_RFSMOK3 (Smoking Status)**: Significant lifestyle factor that influences metabolism, weight patterns, and overall health outcomes.

- **_RFDRHV9 (Heavy Drinker)**: Behavioral risk factor; heavy alcohol consumption is associated with various health outcomes including weight gain.

- **_EDUCAG (Education Level)**: Socioeconomic indicator that often correlates with health literacy, lifestyle choices, and health outcomes.

- **_INCOMG1 (Income Category)**: Socioeconomic variable affecting access to healthcare, healthy food options, and health-related resources.

## Primary Outcomes
- Obesity prevalence and classification
- Identification of demographic and behavioral risk factors associated with obesity
- Understanding socioeconomic disparities in weight-related health outcomes

In [58]:
cols = ["_TOTINDA","_RFBMI5", "_RFSMOK3",
        "_RFDRHV9"] 
data = brfss[cols]

## Renaming Variable Names

In [59]:

# Renaming Variable Names

data = data.rename(columns={ 
                           "_TOTINDA": "Physical_Activity",
                           "WTKG3": "Weight(kg)",
                           "_RFSMOK3": "Smoker",
                           "_RFDRHV9": "Heavy_Drinker",
                           "_RFBMI5": "Obese"
                         })
data.columns

Index(['Physical_Activity', 'Obese', 'Smoker', 'Heavy_Drinker'], dtype='str')

In [60]:
data.head()

   Physical_Activity  Obese  Smoker  Heavy_Drinker
0                1.0    1.0     1.0            1.0
1                1.0    2.0     1.0            1.0
2                1.0    1.0     2.0            1.0
3                1.0    2.0     1.0            1.0
4                2.0    1.0     1.0            1.0

# Recoding Variables from Numeric to Categorical Format

- Recoding Heavy Drinker Status from Numeric to Categorical Format:
 Improves interpretability by using descriptive "Yes"/"No" labels for this binary variable.

- Converting Smoking Status from Numeric Codes to Binary Categories:
  Makes the data self-documenting and prevents numeric codes from being misinterpreted as quantitative.

- Mapping Physical Activity Variable from Numeric to Descriptive Categories:Provides clear, descriptive labels that eliminate ambiguity in understanding activity status.

- Recoding Obesity Status from Numeric to Binary Categorical Format: Clearly communicates health status using straightforward "Yes"/"No" categories.

In [61]:

# Converting the column to integer
data["Heavy_Drinker"] = data["Heavy_Drinker"].astype("Int64")

# Map numeric codes 
data["Heavy_Drinker"] = pd.Categorical(
    data["Heavy_Drinker"].map({
        1: "No",
        2: "Yes",
        9: np.nan
    })
)

In [62]:
# Converting  column to integer 
data["Smoker"] = data["Smoker"].astype("Int64")

# Map numeric codes to categor
data["Smoker"] = pd.Categorical(
    data["Smoker"].map({
        1: "No",
        2: "Yes",
        9: np.nan 
    })
)

In [63]:

# Converting column to integer 
data["Physical_Activity"] = data["Physical_Activity"].astype("Int64")

data["Physical_Activity"] = pd.Categorical(
    data["Physical_Activity"].map({
        1: "Had physical activity or exercise",
        2: "No physical activity or exercise in last 30 days",
        9: np.nan
    })
)

In [64]:
# Converting column to integer 
data["Obese"] = data["Obese"].astype("Int64")

# Mapping numeric codes to categories
data["Obese"] = data["Obese"].map({
    1: "No",
    2: "Yes",
    9: np.nan 
})

In [65]:
data.describe()

                        Physical_Activity   Obese  Smoker Heavy_Drinker
count                              456355  414633  425648        410972
unique                                  2       2       2             2
top     Had physical activity or exercise     Yes      No            No
freq                               350061  286203  378554        386812

## Categorical Variable Analysis
Displaying frequency counts for all categorical variables to understand:
- Class distribution and balance
- Most common categories
- Potential data quality issues

In [66]:
cat_vars = ["Physical_Activity", "Smoker", "Heavy_Drinker","Obese"]

for var in cat_vars:
    print(data[var].value_counts())
    print("\n")

Physical_Activity
Had physical activity or exercise                   350061
No physical activity or exercise in last 30 days    106294
Name: count, dtype: int64


Smoker
No     378554
Yes     47094
Name: count, dtype: int64


Heavy_Drinker
No     386812
Yes     24160
Name: count, dtype: int64


Obese
Yes    286203
No     128430
Name: count, dtype: int64

## Missing Values Imputation

In [ ]:
data.info() # 457669 observations

# Missing values counts by columns
data.isna().sum()

# Rows with missing values
data[data.isna().any(axis=1)]

<class 'pandas.DataFrame'>
RangeIndex: 457670 entries, 0 to 457669
Data columns (total 4 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Physical_Activity  456355 non-null  category
 1   Weight(kg)         421278 non-null  float64
 2   Smoker             425648 non-null  category
 3   Heavy_Drinker      410972 non-null  category
dtypes: category(3), float64(1)
memory usage: 4.8 MB

,Physical_Activity,Weight(kg),Smoker,Heavy_Drinker
25,Had physical activity or exercise,NaN,NaN,NaN
39,Had physical activity or exercise,NaN,No,No
41,Had physical activity or exercise,NaN,No,No
51,No physical activity or exercise in last 30 days,8618.0,No,NaN
54,No physical activity or exercise in last 30 days,NaN,NaN,NaN
...,...,...,...,...
457658,Had physical activity or exercise,NaN,NaN,NaN
457660,Had physical activity or exercise,10206.0,NaN,NaN
457662,No physical activity or exercise in last 30 days,8618.0,NaN,No
457665,Had physical activity or exercise,NaN,NaN,NaN
457668,Had physical activity or exercise,8165.0,No,NaN

## Data Preprocessing