In [8]:
import pandas as pd
import numpy as np

In [9]:
brfss = pd.read_sas("data/LLCP2024.XPT ")

FileNotFoundError: [Errno 2] No such file or directory: 'data/LLCP2024.XPT '

In [10]:
brfss.info()

NameError: name 'brfss' is not defined

In [ ]:
brfss1 = brfs[:228835]
brfss2 = brfs[228835:]

In [ ]:
brfss1.info()

In [ ]:
brfss2.info()

In [ ]:
brfss1.to_parquet("BRFSS_2024_1.parquet.gzip",engine = "fastparquet", compression = "gzip")
brfss2.to_parquet("BRFSS_2024_2.parquet.gzip",engine = "fastparquet", compression = "gzip")

In [5]:
brfss1.to_parquet("BRFSS_2024.parquet.gzip",engine = "fastparquet", compression = "gzip")

NameError: name 'brfss1' is not defined

In [4]:
brfss.describe()

,_STATE,FMONTH,DISPCODE,_PSU,CTELENM1,PVTRESD1,COLGHOUS,STATERE1,CELPHON1,LADULT1,...,_LCSCTSN,_LCSPSTF,DRNKANY6,DROCDY4_,_RFBING6,_DRNKWK3,_RFDRHV9,_FLSHOT7,_PNEUMO3,_AIDTST4
count,457670.000000,457670.000000,457670.000000,4.576700e+05,81730.0,81730.000000,14.0,81730.0,81730.0,81730.000000,...,393433.000000,406226.000000,457670.000000,4.576690e+05,457670.000000,4.576700e+05,457670.000000,179344.000000,179344.000000,414178.000000
mean,30.823537,6.426995,1118.669784,2.024007e+09,1.0,1.000171,1.0,1.0,2.0,1.001835,...,3.420252,8.468687,2.196764,1.000599e+02,1.948965,1.044393e+04,1.869063,2.336850,2.462223,1.999684
std,15.939364,3.356938,38.966920,7.488291e+03,0.0,0.013087,0.0,0.0,0.0,0.042801,...,0.792956,1.892208,2.226566,2.613717e+02,2.418721,3.016653e+04,2.414067,2.602255,2.814818,1.665037
min,1.000000,1.000000,1100.000000,2.024000e+09,1.0,1.000000,1.0,1.0,2.0,1.000000,...,1.000000,1.000000,1.000000,5.397605e-79,1.000000,5.397605e-79,1.000000,1.000000,1.000000,1.000000
25%,18.000000,4.000000,1100.000000,2.024002e+09,1.0,1.000000,1.0,1.0,2.0,1.000000,...,3.000000,9.000000,1.000000,5.397605e-79,1.000000,5.397605e-79,1.000000,1.000000,1.000000,1.000000
50%,31.000000,7.000000,1100.000000,2.024005e+09,1.0,1.000000,1.0,1.0,2.0,1.000000,...,4.000000,9.000000,2.000000,3.000000e+00,1.000000,4.700000e+01,1.000000,1.000000,1.000000,2.000000
75%,44.000000,9.000000,1100.000000,2.024008e+09,1.0,1.000000,1.0,1.0,2.0,1.000000,...,4.000000,9.000000,2.000000,2.900000e+01,1.000000,4.670000e+02,1.000000,2.000000,2.000000,2.000000
max,78.000000,12.000000,1200.000000,2.024044e+09,1.0,2.000000,1.0,1.0,2.0,2.000000,...,4.000000,9.000000,9.000000,9.000000e+02,9.000000,9.990000e+04,9.000000,9.000000,9.000000,9.000000

In [11]:
brfss.head()

NameError: name 'brfss' is not defined

In [ ]:
for col in brfs.columns:
    print(col)

In [7]:
columns_list = brfs.columns.tolist()
print(columns_list)

['_STATE', 'FMONTH', 'IDATE', 'IMONTH', 'IDAY', 'IYEAR', 'DISPCODE', 'SEQNO', '_PSU', 'CTELENM1', 'PVTRESD1', 'COLGHOUS', 'STATERE1', 'CELPHON1', 'LADULT1', 'NUMADULT', 'RESPSLC1', 'LANDSEX3', 'SAFETIME', 'CTELNUM1', 'CELLFON5', 'CADULT1', 'CELLSEX3', 'PVTRESD3', 'CCLGHOUS', 'CSTATE1', 'LANDLINE', 'HHADULT', 'SEXVAR', 'GENHLTH', 'PHYSHLTH', 'MENTHLTH', 'POORHLTH', 'PRIMINS2', 'PERSDOC3', 'MEDCOST1', 'CHECKUP1', 'EXERANY2', 'LASTDEN4', 'RMVTETH4', 'CVDINFR4', 'CVDCRHD4', 'CVDSTRK3', 'ASTHMA3', 'ASTHNOW', 'CHCSCNC1', 'CHCOCNC1', 'CHCCOPD3', 'ADDEPEV3', 'CHCKDNY2', 'HAVARTH4', 'DIABETE4', 'DIABAGE4', 'MARITAL', 'EDUCA', 'RENTHOM1', 'NUMHHOL4', 'NUMPHON4', 'CPDEMO1C', 'VETERAN3', 'EMPLOY1', 'CHILDREN', 'INCOME3', 'PREGNANT', 'WEIGHT2', 'HEIGHT3', 'DEAF', 'BLIND', 'DECIDE', 'DIFFWALK', 'DIFFDRES', 'DIFFALON', 'HADMAM', 'HOWLONG', 'CERVSCRN', 'CRVCLCNC', 'CRVCLPAP', 'CRVCLHPV', 'HADHYST2', 'HADSIGM4', 'COLNSIGM', 'COLNTES1', 'SIGMTES1', 'LASTSIG4', 'COLNCNCR', 'VIRCOLO1', 'VCLNTES2', 'SMALSTOL', 'STOLTEST', 'STOOLDN2', 'BLDSTFIT', 'SDNATES1', 'SMOKE100', 'SMOKDAY2', 'USENOW3', 'ECIGNOW3', 'LCSFIRST', 'LCSNUMCG', 'LCSCTSC1', 'LCSSCNCR', 'LCSCTWHN', 'ALCDAY4', 'AVEDRNK4', 'DRNK3GE5', 'MAXDRNKS', 'FLUSHOT7', 'FLSHTMY3', 'IMFVPLA5', 'PNEUVAC4', 'HIVTST7', 'HIVTSTD3', 'HIVRISK5', 'PDIABTS1', 'PREDIAB2', 'DIABTYPE', 'INSULIN1', 'CHKHEMO3', 'EYEEXAM1', 'DIABEYE1', 'DIABEDU1', 'FEETSORE', 'ARTHEXER', 'SHINGLE2', 'HPVADVC4', 'HPVADSH1', 'TETANUS1', 'CNCRDIFF', 'CNCRAGE', 'CNCRTYP2', 'CSRVTRT3', 'CSRVDOC1', 'CSRVSUM', 'CSRVRTRN', 'CSRVINST', 'CSRVINSR', 'CSRVDEIN', 'CSRVCLIN', 'CSRVPAIN', 'CSRVCTL2', 'PSATEST1', 'PSATIME1', 'PCPSARS2', 'PSASUGS1', 'PCSTALK2', 'CIMEMLO1', 'CDWORRY', 'CDDISCU1', 'CDHOUS1', 'CDSOCIA1', 'CAREGIV1', 'CRGVREL5', 'CRGVPRB4', 'CRGVALZD', 'CRGVNURS', 'CRGVPER2', 'CRGVHOU2', 'CRGVHRS2', 'CRGVLNG2', 'ACEDEPRS', 'ACEDRINK', 'ACEDRUGS', 'ACEPRISN', 'ACEDIVRC', 'ACEPUNCH', 'ACEHURT1', 'ACESWEAR', 'ACETOUCH', 'ACETTHEM', 'ACEHVSEX', 'ACEADSAF', 'ACEADNED', 'LSATISFY', 'EMTSUPRT', 'SDLONELY', 'SDHEMPLY', 'FOODSTMP', 'SDHFOOD1', 'SDHBILLS', 'SDHUTILS', 'SDHTRNSP', 'HOWSAFE1', 'MARIJAN1', 'MARJSMOK', 'MARJEAT', 'MARJVAPE', 'MARJDAB', 'MARJOTHR', 'USEMRJN4', 'LASTSMK2', 'STOPSMK2', 'MENTCIGS', 'MENTECIG', 'HEATTBCO', 'SSBSUGR2', 'SSBFRUT3', 'FIREARM5', 'GUNLOAD', 'LOADULK2', 'RCSGEND1', 'RCSXBRTH', 'RCSRLTN2', 'CASTHDX2', 'CASTHNO2', 'SOMALE', 'SOFEMALE', 'HADSEX', 'PFPPRVN4', 'TYPCNTR9', 'NOBCUSE8', 'QSTVER', 'QSTLANG', 'HPVDSHT', 'ICFQSTVR', '_METSTAT', '_URBSTAT', 'MSCODE', '_STSTR', '_STRWT', '_RAWRAKE', '_WT2RAKE', '_IMPRACE', '_CHISPNC', '_CRACE1', 'CAGEG', '_CLLCPWT', '_DUALUSE', '_DUALCOR', '_LLCPWT2', '_LLCPWT', '_RFHLTH', '_PHYS14D', '_MENT14D', '_HLTHPL2', '_HCVU654', '_TOTINDA', '_EXTETH3', '_ALTETH3', '_DENVST3', '_MICHD', '_LTASTH1', '_CASTHM1', '_ASTHMS1', '_DRDXAR2', '_MRACE1', '_HISPANC', '_RACE', '_RACEG21', '_RACEGR3', '_RACEPRV', '_SEX', '_AGEG5YR', '_AGE65YR', '_AGE80', '_AGE_G', 'HTIN4', 'HTM4', 'WTKG3', '_BMI5', '_BMI5CAT', '_RFBMI5', '_CHLDCNT', '_EDUCAG', '_INCOMG1', '_RFMAM23', '_MAM402Y', '_CRVSCRN', '_RFPAP37', '_HPV5YR1', '_PAPHPV1', '_HADCOLN', '_CLNSCP2', '_HADSIGM', '_SGMSCP2', '_SGMS102', '_RFBLDS6', '_STOLDN2', '_VIRCOL2', '_SBONTI2', '_CRCREC3', '_SMOKER3', '_RFSMOK3', '_CURECI3', 'LCSLAST_', 'LCSNUMC_', '_LCSAGE', '_LCSYSMK', '_PACKDAY', '_PACKYRS', '_LCSYQTS', '_LCSSMKG', '_LCSELIG', '_LCSCTSN', '_LCSPSTF', 'DRNKANY6', 'DROCDY4_', '_RFBING6', '_DRNKWK3', '_RFDRHV9', '_FLSHOT7', '_PNEUMO3', '_AIDTST4']

## Selecting Relevant Variables

In [4]:
cols = ["_TOTINDA","WTKG3", "_RFSMOK3",
        "_RFDRHV9"] 
data = brfs[cols]

## Data Processing

In [5]:

# Renaming Variable Names

data = data.rename(columns={ 
                           "_TOTINDA": "Physical_Activity",
                           "WTKG3": "Weight(kg)",
                           "_RFSMOK3": "Smoker",
                           "_RFDRHV9": "Heavy_Drinker",
                
                         })
data.columns

Index(['Age_group', 'Sex', 'BMI', 'Obese', 'Height(m)', 'Physical_Activity',
       'Weight(kg)', 'Smoker', 'Heavy_Drinker', 'Education_level',
       'Income_Cat'],
      dtype='object')

In [6]:
data.head()

,Age_group,Sex,BMI,Obese,Height(m),Physical_Activity,Weight(kg),Smoker,Heavy_Drinker,Education_level,Income_Cat
0,6.0,2.0,2249.0,1.0,163.0,1.0,5942.0,1.0,1.0,2.0,9.0
1,6.0,1.0,2583.0,2.0,178.0,1.0,8165.0,1.0,1.0,4.0,7.0
2,5.0,1.0,2253.0,1.0,198.0,1.0,8845.0,2.0,1.0,3.0,9.0
3,6.0,1.0,2509.0,2.0,173.0,1.0,7484.0,1.0,1.0,4.0,4.0
4,4.0,1.0,1977.0,1.0,173.0,2.0,5897.0,1.0,1.0,3.0,2.0

## Mapping Values In Categorical Variables

In [9]:

# Converting the column to integer
data["Heavy_Drinker"] = data["Heavy_Drinker"].astype("Int64")

# Map numeric codes 
data["Heavy_Drinker"] = pd.Categorical(
    data["Heavy_Drinker"].map({
        1: "No",
        2: "Yes",
        9: np.nan
    })
)

In [10]:
# Converting  column to integer 
data["Smoker"] = data["Smoker"].astype("Int64")

# Map numeric codes to categor
data["Smoker"] = pd.Categorical(
    data["Smoker"].map({
        1: "No",
        2: "Yes",
        9: np.nan 
    })
)

In [12]:
# Converting to integer 
data["Sex"] = data["Sex"].astype("Int64")

# Mapping numeric codes to categories
data["Sex"] = data["Sex"].map({
    1: "Male",
    2: "Female"
})

In [16]:

# Converting column to integer 
data["Physical_Activity"] = data["Physical_Activity"].astype("Int64")

data["Physical_Activity"] = pd.Categorical(
    data["Physical_Activity"].map({
        1: "Had physical activity or exercise",
        2: "No physical activity or exercise in last 30 days",
        9: np.nan
    })
)

In [17]:
data.describe(include = "category")

,Age_group,Physical_Activity,Smoker,Heavy_Drinker,Education_level,Income_Cat
count,457670,456355,425648,410972,455307,370247
unique,6,2,2,2,4,7
top,Age 65 or older,Had physical activity or exercise,No,No,Graduated from College or Technical School,"$50,000 < $100,000"
freq,172826,350061,378554,386812,191549,112409

In [18]:
data.describe()

                 BMI      Height(m)     Weight(kg)
count  414633.000000  433610.000000  421278.000000
mean     2855.680093     170.165995    8300.484516
std       658.616131      10.822765    2141.833796
min      1200.000000      91.000000    2268.000000
25%      2414.000000     163.000000    6804.000000
50%      2744.000000     170.000000    8074.000000
75%      3175.000000     178.000000    9525.000000
max      9984.000000     241.000000   29030.000000

## Distributions of Categorical Variables

In [21]:
cat_vars = ["Sex", "Physical_Activity", "Smoker", "Heavy_Drinker"]

for var in cat_vars:
    print(data[var].value_counts())
    print("\n")

Age_group
Age 65 or older    172826
Age 55 to 64        80280
Age 45 to 54        64458
Age 35 to 44        60418
Age 25 to 34        49994
Age 18 to 24        29694
Name: count, dtype: int64


Sex
Female    240163
Male      217507
Name: count, dtype: int64


Obese
Yes    286203
No     128430
Name: count, dtype: int64


Physical_Activity
Had physical activity or exercise                   350061
No physical activity or exercise in last 30 days    106294
Name: count, dtype: int64


Smoker
No     378554
Yes     47094
Name: count, dtype: int64


Heavy_Drinker
No     386812
Yes     24160
Name: count, dtype: int64


Education_level
Graduated from College or Technical School    191549
Attended College or Technical School          120732
Graduated High School                         115877
Did not graduate High School                   27149
Don’t know/Not sure/Missing                        0
Name: count, dtype: int64


Income_Cat
$50,000 < $100,000     112409
$100,000 < $200,000     82453
$35,000 < $50,000       49686
$25,000 < $35,000       41702
$15,000 < $25,000       33503
$200,000 or more        29694
Less than $15,000       20800
Missing/Don’t know          0
Name: count, dtype: int64

## Missing Values Imputation

In [32]:
data.info() # 457669 observations

# Missing values counts by columns
data.isna().sum()

# Rows with missing values
data[data.isna().any(axis=1)]

Age_group                0
Sex                      0
BMI                  43037
Obese                43037
Height(m)            24060
Physical_Activity     1315
Weight(kg)           36392
Smoker               32022
Heavy_Drinker        46698
Education_level       2363
Income_Cat           87423
dtype: int64

## Data Preprocessing