# Data Pre-Processing

In [1]:
import sys
print(sys.executable)

c:\Users\lulum\AppData\Local\Programs\Python\Python314\python.exe

In [2]:
# Packages

#import os
#os.chdir(r"C:\Users\lulum\Documents\GitHub\group-project-team2")
import os
os.chdir(r"C:\Users\lulum\Documents\GitHub\group-project-team2")

import pandas as pd
import numpy as np
import  pyreadstat

In [ ]:
import os
os.getcwd()

In [ ]:
import os
print(os.path.exists("data_acquisition/brfss2022_part1.parquet.gzip"))

In [ ]:
import os
print(os.listdir())

In [ ]:
import os
print(os.listdir(r"C:\Users\lulum\Documents\GitHub"))

# 2022

In [3]:
# Data Import
#brfss2022_1 = pd.read_parquet("data_acquisition/brfss2022_part1.parquet.gzip")
#brfss2022_2 = pd.read_parquet("data_acquisition/brfss2022_part2.parquet.gzip")
brfss2022_1 = pd.read_parquet(r"C:\Users\lulum\Documents\GitHub\group-project-team2\checkpoint\data_acquisition\brfss2022_part1.parquet.gzip")
brfss2022_2 = pd.read_parquet(r"C:\Users\lulum\Documents\GitHub\group-project-team2\checkpoint\data_acquisition\brfss2022_part2.parquet.gzip")

brfss2022 = pd.concat([brfss2022_1, brfss2022_2], axis = 0)

In [4]:
# Selecting relevant variables

col=["_AGE_G", "SEXVAR","_BMI5","_RFBMI5","HTM4", "_TOTINDA","WTKG3", "_RFSMOK3",
        "_EDUCAG" , "_INCOMG1","DIABETE4", "ASTHNOW", "CHCKDNY2", "_DRDXAR2","_RFDRHV8"]

data2022=brfss2022[col]

data2022.head()

,_AGE_G,SEXVAR,_BMI5,_RFBMI5,HTM4,_TOTINDA,WTKG3,_RFSMOK3,_EDUCAG,_INCOMG1,DIABETE4,ASTHNOW,CHCKDNY2,_DRDXAR2,_RFDRHV8
0,6.0,2.0,NaN,9.0,NaN,2.0,NaN,1.0,4.0,9.0,1.0,NaN,2.0,2.0,1.0
1,6.0,2.0,2657.0,2.0,160.0,2.0,6804.0,1.0,2.0,3.0,3.0,NaN,2.0,2.0,1.0
2,5.0,2.0,2561.0,2.0,157.0,1.0,6350.0,1.0,4.0,6.0,3.0,NaN,2.0,2.0,1.0
3,6.0,2.0,2330.0,1.0,165.0,1.0,6350.0,2.0,2.0,9.0,3.0,1.0,2.0,1.0,1.0
4,3.0,2.0,2177.0,1.0,157.0,1.0,5398.0,1.0,3.0,3.0,3.0,NaN,2.0,2.0,1.0

In [5]:
# Creating the missing variables

data2022["High_Cholesterol"] = float(999)
data2022["High_BP"] = float(999)

# Adding the Year indicator
data2022["Year"] = int(2022)

C:\Users\lulum\AppData\Local\Temp\ipykernel_41220\2482729506.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2022["High_Cholesterol"] = float(999)
C:\Users\lulum\AppData\Local\Temp\ipykernel_41220\2482729506.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2022["High_BP"] = float(999)
C:\Users\lulum\AppData\Local\Temp\ipykernel_41220\2482729506.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2022["Year"] = int(2022)

In [6]:
# Renaming Variables

data2022 = data2022.rename(columns={ "SEXVAR": "Sex",
                           "_BMI5": "BMI",
                           "_AGE_G": "Age_group",
                           "_RFBMI5": "Obese",
                           "HTM4": "Height_in_m",
                           "_TOTINDA": "Physical_Activity",
                          "_RFDRHV8": "Heavy_Drinker",
                           "WTKG3": "Weight_in_kg",
                           "_RFSMOK3": "Smoker",
                           "_EDUCAG": "Education_level",
                           "_INCOMG1": "Income_Cat",
                             "DIABETE4": "Diabetes",
                             "ASTHNOW": "Asthma",
                             "CHCKDNY2": "Kidney_Disease",
                             "_DRDXAR2": "Arthritis"
                         })
data2022.info()

<class 'pandas.core.frame.DataFrame'>
Index: 445132 entries, 0 to 222565
Data columns (total 18 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Age_group          445132 non-null  float64
 1   Sex                445132 non-null  float64
 2   BMI                396326 non-null  float64
 3   Obese              445132 non-null  float64
 4   Height_in_m        416480 non-null  float64
 5   Physical_Activity  445132 non-null  float64
 6   Weight_in_kg       403054 non-null  float64
 7   Smoker             445132 non-null  float64
 8   Education_level    445132 non-null  float64
 9   Income_Cat         445132 non-null  float64
 10  Diabetes           445129 non-null  float64
 11  Asthma             66694 non-null   float64
 12  Kidney_Disease     445130 non-null  float64
 13  Arthritis          442499 non-null  float64
 14  Heavy_Drinker      445132 non-null  float64
 15  High_Cholesterol   445132 non-null  float64
 16  High_BP            445132 non-null  float64
 17  Year               445132 non-null  int64
dtypes: float64(17), int64(1)
memory usage: 64.5 MB

In [7]:
data2022.head()

,Age_group,Sex,BMI,Obese,Height_in_m,Physical_Activity,Weight_in_kg,Smoker,Education_level,Income_Cat,Diabetes,Asthma,Kidney_Disease,Arthritis,Heavy_Drinker,High_Cholesterol,High_BP,Year
0,6.0,2.0,NaN,9.0,NaN,2.0,NaN,1.0,4.0,9.0,1.0,NaN,2.0,2.0,1.0,999.0,999.0,2022
1,6.0,2.0,2657.0,2.0,160.0,2.0,6804.0,1.0,2.0,3.0,3.0,NaN,2.0,2.0,1.0,999.0,999.0,2022
2,5.0,2.0,2561.0,2.0,157.0,1.0,6350.0,1.0,4.0,6.0,3.0,NaN,2.0,2.0,1.0,999.0,999.0,2022
3,6.0,2.0,2330.0,1.0,165.0,1.0,6350.0,2.0,2.0,9.0,3.0,1.0,2.0,1.0,1.0,999.0,999.0,2022
4,3.0,2.0,2177.0,1.0,157.0,1.0,5398.0,1.0,3.0,3.0,3.0,NaN,2.0,2.0,1.0,999.0,999.0,2022

In [8]:
# Exporting the file
# pyreadstat.write_dta(data2022,dst_path = r"C:\Users\lulum\Documents\GitHub\group-project-team2\checkpoint\data_acquisition")
data2022.to_parquet(
    r"C:\Users\lulum\Documents\GitHub\group-project-team2\checkpoint\data2022.parquet",
    index=False
)

# 2023

In [9]:
# Data Import
brfss2023_1 = pd.read_parquet(r"C:\Users\lulum\Documents\GitHub\group-project-team2\checkpoint\data_acquisition\brfss2023_part1.parquet.gzip")
brfss2023_2 = pd.read_parquet(r"C:\Users\lulum\Documents\GitHub\group-project-team2\checkpoint\data_acquisition\brfss2023_part2.parquet.gzip")

brfss2023 = pd.concat([brfss2023_1, brfss2023_2], axis = 0)

In [10]:
# Selecting Relevant Variables

col=["_AGE_G", "SEXVAR","_BMI5","_RFBMI5","HTM4", "_TOTINDA","WTKG3", "_RFSMOK3",
        "_EDUCAG" , "_INCOMG1","DIABETE4", "ASTHNOW", "CHCKDNY2", "_DRDXAR2", "TOLDHI3", "BPMEDS1","_RFDRHV8"]

data2023=brfss2023[col]

# Adding the Year indicator
data2023["Year"] = int(2023)

data2023.head()

C:\Users\lulum\AppData\Local\Temp\ipykernel_41220\602139361.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2023["Year"] = int(2023)

,_AGE_G,SEXVAR,_BMI5,_RFBMI5,HTM4,_TOTINDA,WTKG3,_RFSMOK3,_EDUCAG,_INCOMG1,DIABETE4,ASTHNOW,CHCKDNY2,_DRDXAR2,TOLDHI3,BPMEDS1,_RFDRHV8,Year
0,6.0,2.0,3047.0,2.0,160.0,2.0,7802.0,1.0,3.0,9.0,1.0,NaN,2.0,2.0,2.0,1.0,1.0,2023
1,6.0,2.0,2856.0,2.0,145.0,1.0,5987.0,1.0,3.0,9.0,3.0,NaN,2.0,1.0,1.0,2.0,1.0,2023
2,6.0,2.0,2231.0,1.0,163.0,1.0,5897.0,1.0,2.0,1.0,3.0,1.0,2.0,1.0,1.0,1.0,1.0,2023
3,6.0,2.0,2744.0,2.0,168.0,1.0,7711.0,1.0,3.0,9.0,3.0,NaN,2.0,1.0,2.0,NaN,1.0,2023
4,6.0,2.0,2585.0,2.0,173.0,1.0,7711.0,1.0,3.0,5.0,1.0,NaN,2.0,1.0,2.0,1.0,1.0,2023

In [11]:
# Renaming Variables

data2023 = data2023.rename(columns={ "SEXVAR": "Sex",
                           "_BMI5": "BMI",
                           "_AGE_G": "Age_group",
                           "_RFBMI5": "Obese",
                           "HTM4": "Height_in_m",
                           "_TOTINDA": "Physical_Activity",
                           "WTKG3": "Weight_in_kg",
                           "_RFSMOK3": "Smoker",
                           "_RFDRHV8": "Heavy_Drinker",
                           "_EDUCAG": "Education_level",
                           "_INCOMG1": "Income_Cat",
                             "DIABETE4": "Diabetes",
                             "ASTHNOW": "Asthma",
                             "CHCKDNY2": "Kidney_Disease",
                             "_DRDXAR2": "Arthritis",
                             "TOLDHI3": "High_Cholesterol",
                             "BPMEDS1": "High_BP"
                         })
data2023.info()

<class 'pandas.core.frame.DataFrame'>
Index: 433323 entries, 0 to 216661
Data columns (total 18 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Age_group          433323 non-null  float64
 1   Sex                433323 non-null  float64
 2   BMI                392788 non-null  float64
 3   Obese              433323 non-null  float64
 4   Height_in_m        411182 non-null  float64
 5   Physical_Activity  433323 non-null  float64
 6   Weight_in_kg       399172 non-null  float64
 7   Smoker             433323 non-null  float64
 8   Education_level    433323 non-null  float64
 9   Income_Cat         433323 non-null  float64
 10  Diabetes           433318 non-null  float64
 11  Asthma             64366 non-null   float64
 12  Kidney_Disease     433320 non-null  float64
 13  Arthritis          430763 non-null  float64
 14  High_Cholesterol   381511 non-null  float64
 15  High_BP            176222 non-null  float64
 16  Heavy_Drinker      433323 non-null  float64
 17  Year               433323 non-null  int64
dtypes: float64(17), int64(1)
memory usage: 62.8 MB

In [12]:
# Exporting The file
#pyreadstat.write_dta(data2023 ,dst_path = "Output/BRFSS23.dta")
data2023.to_parquet(
    r"C:\Users\lulum\Documents\GitHub\group-project-team2\checkpoint\data2023.parquet",
    index=False
)

# 2024

In [13]:
# Data Import
brfss2024_1 = pd.read_parquet(r"C:\Users\lulum\Documents\GitHub\group-project-team2\checkpoint\data_acquisition\BRFSS_2024_1.parquet.gzip")
brfss2024_2 = pd.read_parquet(r"C:\Users\lulum\Documents\GitHub\group-project-team2\checkpoint\data_acquisition\BRFSS_2024_2.parquet.gzip")

brfss2024 = pd.concat([brfss2024_1, brfss2024_2], axis = 0)

MemoryError: Unable to allocate 14.0 MiB for an array with shape (4, 457670) and data type object

In [ ]:
# Selecting Relevant Variables

cols = ["_AGE_G", "SEXVAR","_BMI5","_RFBMI5","HTM4", "_TOTINDA","WTKG3", "_RFSMOK3",
        "_RFDRHV9","_EDUCAG" , "_INCOMG1","DIABETE4", "ASTHNOW", "CHCKDNY2", "_DRDXAR2"]

data2024 = brfss2024[cols]
data2024.head()

In [ ]:
# Creating the missing variables

data2024["High_Cholesterol"] = float(999)
data2024["High_BP"] = float(999)

# Adding the Year indicator
data2024["Year"] = int(2024)

In [ ]:
# Renaming Variables

data2024 = data2024.rename(columns={ "SEXVAR": "Sex",
                           "_BMI5": "BMI",
                           "_AGE_G": "Age_group",
                           "_RFBMI5": "Obese",
                           "HTM4": "Height_in_m",
                           "_TOTINDA": "Physical_Activity",
                           "WTKG3": "Weight_in_kg",
                           "_RFSMOK3": "Smoker",
                           "_RFDRHV9": "Heavy_Drinker",
                           "_EDUCAG": "Education_level",
                           "_INCOMG1": "Income_Cat",
                             "DIABETE4": "Diabetes",
                             "ASTHNOW": "Asthma",
                             "CHCKDNY2": "Kidney_Disease",
                             "_DRDXAR2": "Arthritis"
                         })
data2024.info()

In [ ]:
# Exporting The file
pyreadstat.write_dta(data2024 ,dst_path = "Output/BRFSS24.dta")

# Data Merging

In [ ]:
# Merging the Three Files

brfss = pd.concat([data2022, data2023, data2024], axis = 0)
brfss = brfss.reset_index(drop=True)

In [ ]:
brfss.info()

In [ ]:
# Exporting The file
pyreadstat.write_dta(brfss ,dst_path = "Output/BRFSS_Merged.dta")