In [8]:
import pandas as pd
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import SMOTE
import numpy as np
import optuna
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score, recall_score, precision_score, confusion_matrix, classification_report

In [2]:
df_2024 = pd.read_parquet("data_2024.parquet")

In [3]:
df_2024.head()

,_ASTHMS1,CHCKDNY2,_DRDXAR2,_EDUCAG,_INCOMG1,_AGE_G,_SEX,_BMI5,_RFDRHV9,_RFSMOK3,_TOTINDA,DIABETE4,year,DIABETE_BIN
0,3.0,0.0,1.0,2.0,9.0,6.0,1.0,2249.0,1.0,1.0,1.0,3.0,2024,0.0
1,3.0,0.0,1.0,4.0,7.0,6.0,0.0,2583.0,1.0,1.0,1.0,3.0,2024,0.0
2,3.0,0.0,1.0,3.0,9.0,5.0,0.0,2253.0,1.0,0.0,1.0,3.0,2024,0.0
3,3.0,0.0,1.0,4.0,4.0,6.0,0.0,2509.0,1.0,1.0,1.0,3.0,2024,0.0
4,3.0,0.0,0.0,3.0,2.0,4.0,0.0,1977.0,1.0,1.0,2.0,3.0,2024,0.0

In [4]:
target_col = "DIABETE_BIN"
df_2024 = df_2024.dropna()
X = df_2024.drop(columns=[target_col, "DIABETE4","year"])
y = df_2024[target_col]
X

,_ASTHMS1,CHCKDNY2,_DRDXAR2,_EDUCAG,_INCOMG1,_AGE_G,_SEX,_BMI5,_RFDRHV9,_RFSMOK3,_TOTINDA
0,3.0,0.0,1.0,2.0,9.0,6.0,1.0,2249.0,1.0,1.0,1.0
1,3.0,0.0,1.0,4.0,7.0,6.0,0.0,2583.0,1.0,1.0,1.0
2,3.0,0.0,1.0,3.0,9.0,5.0,0.0,2253.0,1.0,0.0,1.0
3,3.0,0.0,1.0,4.0,4.0,6.0,0.0,2509.0,1.0,1.0,1.0
4,3.0,0.0,0.0,3.0,2.0,4.0,0.0,1977.0,1.0,1.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...
453234,3.0,0.0,0.0,1.0,4.0,3.0,0.0,2466.0,1.0,1.0,1.0
453235,3.0,0.0,1.0,2.0,1.0,6.0,0.0,2986.0,1.0,1.0,2.0
453237,3.0,0.0,0.0,1.0,4.0,6.0,0.0,2066.0,0.0,0.0,2.0
453238,0.0,0.0,0.0,4.0,5.0,6.0,0.0,2437.0,1.0,1.0,2.0
453240,3.0,0.0,1.0,1.0,3.0,5.0,0.0,2647.0,1.0,1.0,1.0

## SMOTE

In [9]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)


smote = SMOTE(random_state=42)

X_train_res, y_train_res = smote.fit_resample(X_train, y_train)

print("Before SMOTE:", y_train.value_counts().to_dict())
print("After SMOTE:", y_train_res.value_counts().to_dict())


model = XGBClassifier(
    n_estimators=500,
    learning_rate=0.05,
    max_depth=5,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    eval_metric="logloss"
)

model.fit(X_train_res, y_train_res)


y_prob = model.predict_proba(X_test)[:, 1]

y_pred = (y_prob >= 0.5).astype(int)

print("\nAccuracy:", accuracy_score(y_test, y_pred))
print("Precision (class 1):", precision_score(y_test, y_pred, pos_label=1))
print("Recall (class 1):", recall_score(y_test, y_pred, pos_label=1))
print("F1 (class 1):", f1_score(y_test, y_pred, pos_label=1))

print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

print("\nFull Report:\n", classification_report(y_test, y_pred))

print("\nMacro F1:", f1_score(y_test, y_pred, average="macro"))
print("Macro Recall:", recall_score(y_test, y_pred, average="macro"))

Before SMOTE: {0.0: 248805, 1.0: 51398}
After SMOTE: {0.0: 248805, 1.0: 248805}

Accuracy: 0.8298223874432052
Precision (class 1): 0.5106966538672518
Recall (class 1): 0.14490272373540855
F1 (class 1): 0.2257516973811833

Confusion Matrix:
 [[60417  1784]
 [10988  1862]]

Full Report:
               precision    recall  f1-score   support

         0.0       0.85      0.97      0.90     62201
         1.0       0.51      0.14      0.23     12850

    accuracy                           0.83     75051
   macro avg       0.68      0.56      0.57     75051
weighted avg       0.79      0.83      0.79     75051


Macro F1: 0.5650785940762779
Macro Recall: 0.5581107564112003

## SMOTE + OPTUNA

In [14]:

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

smote = SMOTE(random_state=42)
X_train_res, y_train_res = smote.fit_resample(X_train, y_train)

def objective(trial):

    params = {
        "n_estimators": trial.suggest_int("n_estimators", 200, 800),
        "max_depth": trial.suggest_int("max_depth", 3, 8),
        "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.2),
        "subsample": trial.suggest_float("subsample", 0.6, 1.0),
        "colsample_bytree": trial.suggest_float("colsample_bytree", 0.6, 1.0),
        "min_child_weight": trial.suggest_int("min_child_weight", 1, 10),
        "gamma": trial.suggest_float("gamma", 0, 5),
        "random_state": 42,
        "eval_metric": "logloss"
    }

    model = XGBClassifier(**params)
    model.fit(X_train_res, y_train_res)

    y_prob = model.predict_proba(X_test)[:, 1]

    best_f1 = 0
    for t in [0.2, 0.3, 0.4, 0.5]:
        y_pred = (y_prob >= t).astype(int)
        f1 = f1_score(y_test, y_pred, pos_label=1)
        best_f1 = max(best_f1, f1)

    return best_f1

study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=30)

print("Best params:", study.best_params)
print("Best F1:", study.best_value)

[I 2026-04-19 23:27:35,310] A new study created in memory with name: no-name-64f5c05b-e5ff-437c-af0c-c7cc43638d3d
[I 2026-04-19 23:27:52,946] Trial 0 finished with value: 0.43467557587480216 and parameters: {'n_estimators': 380, 'max_depth': 6, 'learning_rate': 0.06971951347533656, 'subsample': 0.6251625498113422, 'colsample_bytree': 0.9704404914128109, 'min_child_weight': 7, 'gamma': 3.363578219819673}. Best is trial 0 with value: 0.43467557587480216.
[I 2026-04-19 23:28:12,514] Trial 1 finished with value: 0.43493813405265935 and parameters: {'n_estimators': 753, 'max_depth': 8, 'learning_rate': 0.1523316239608964, 'subsample': 0.7179049747122508, 'colsample_bytree': 0.8532301762366619, 'min_child_weight': 10, 'gamma': 4.401360939733563}. Best is trial 1 with value: 0.43493813405265935.
[I 2026-04-19 23:28:55,065] Trial 2 finished with value: 0.43615317618632876 and parameters: {'n_estimators': 625, 'max_depth': 8, 'learning_rate': 0.01342199458441444, 'subsample': 0.7749672566752963, 'colsample_bytree': 0.6935256556562626, 'min_child_weight': 7, 'gamma': 0.48424130330629256}. Best is trial 2 with value: 0.43615317618632876.
[I 2026-04-19 23:29:05,508] Trial 3 finished with value: 0.43636363636363634 and parameters: {'n_estimators': 302, 'max_depth': 6, 'learning_rate': 0.1525504140883632, 'subsample': 0.6047820858197358, 'colsample_bytree': 0.8511846037184909, 'min_child_weight': 5, 'gamma': 4.666210368765462}. Best is trial 3 with value: 0.43636363636363634.
[I 2026-04-19 23:29:17,870] Trial 4 finished with value: 0.4365070093457944 and parameters: {'n_estimators': 349, 'max_depth': 3, 'learning_rate': 0.1387739750223605, 'subsample': 0.8095121623028811, 'colsample_bytree': 0.9452648992858986, 'min_child_weight': 9, 'gamma': 1.6064398013716592}. Best is trial 4 with value: 0.4365070093457944.
[I 2026-04-19 23:29:54,330] Trial 5 finished with value: 0.43577310418041487 and parameters: {'n_estimators': 684, 'max_depth': 8, 'learning_rate': 0.019474362744398555, 'subsample': 0.7391322180986668, 'colsample_bytree': 0.8196678544537708, 'min_child_weight': 10, 'gamma': 4.800804815573402}. Best is trial 4 with value: 0.4365070093457944.
[I 2026-04-19 23:30:19,777] Trial 6 finished with value: 0.4328353704542025 and parameters: {'n_estimators': 457, 'max_depth': 7, 'learning_rate': 0.10510515883059038, 'subsample': 0.7491290494699123, 'colsample_bytree': 0.6673793229478633, 'min_child_weight': 10, 'gamma': 0.6507002079002355}. Best is trial 4 with value: 0.4365070093457944.
[I 2026-04-19 23:30:36,135] Trial 7 finished with value: 0.4328433857070451 and parameters: {'n_estimators': 372, 'max_depth': 5, 'learning_rate': 0.1930261327864199, 'subsample': 0.6236195009579424, 'colsample_bytree': 0.8278098455868512, 'min_child_weight': 4, 'gamma': 1.4662127714211466}. Best is trial 4 with value: 0.4365070093457944.
[I 2026-04-19 23:30:48,212] Trial 8 finished with value: 0.43776677479938536 and parameters: {'n_estimators': 310, 'max_depth': 3, 'learning_rate': 0.10544802842427721, 'subsample': 0.6697850190170869, 'colsample_bytree': 0.9099241063557251, 'min_child_weight': 4, 'gamma': 1.39217260181068}. Best is trial 8 with value: 0.43776677479938536.
[I 2026-04-19 23:31:05,331] Trial 9 finished with value: 0.4354913833255706 and parameters: {'n_estimators': 498, 'max_depth': 7, 'learning_rate': 0.08627090290695853, 'subsample': 0.6382650131481281, 'colsample_bytree': 0.9101502668394474, 'min_child_weight': 8, 'gamma': 4.807723650960564}. Best is trial 8 with value: 0.43776677479938536.
[I 2026-04-19 23:31:13,245] Trial 10 finished with value: 0.43006863290669634 and parameters: {'n_estimators': 205, 'max_depth': 3, 'learning_rate': 0.05611784318386276, 'subsample': 0.9525956790241221, 'colsample_bytree': 0.7380861392570672, 'min_child_weight': 1, 'gamma': 2.686890184783906}. Best is trial 8 with value: 0.43776677479938536.
[I 2026-04-19 23:31:22,875] Trial 11 finished with value: 0.43694724647509253 and parameters: {'n_estimators': 247, 'max_depth': 3, 'learning_rate': 0.11933247799629436, 'subsample': 0.8547268673993521, 'colsample_bytree': 0.9868889557200531, 'min_child_weight': 3, 'gamma': 1.9206875503393874}. Best is trial 8 with value: 0.43776677479938536.
[I 2026-04-19 23:31:30,355] Trial 12 finished with value: 0.4341318230415812 and parameters: {'n_estimators': 211, 'max_depth': 4, 'learning_rate': 0.11850251011021488, 'subsample': 0.8722974781057554, 'colsample_bytree': 0.9995555685991923, 'min_child_weight': 3, 'gamma': 1.7626666523476076}. Best is trial 8 with value: 0.43776677479938536.
[I 2026-04-19 23:31:40,062] Trial 13 finished with value: 0.43584271305364714 and parameters: {'n_estimators': 279, 'max_depth': 4, 'learning_rate': 0.18528819885828762, 'subsample': 0.8879419851779338, 'colsample_bytree': 0.9081643594324481, 'min_child_weight': 2, 'gamma': 2.357930224729065}. Best is trial 8 with value: 0.43776677479938536.
[I 2026-04-19 23:32:03,016] Trial 14 finished with value: 0.4355550220568376 and parameters: {'n_estimators': 575, 'max_depth': 4, 'learning_rate': 0.12404029458102409, 'subsample': 0.8418624061094776, 'colsample_bytree': 0.9040216640741116, 'min_child_weight': 4, 'gamma': 0.05725887835822885}. Best is trial 8 with value: 0.43776677479938536.
[I 2026-04-19 23:32:18,236] Trial 15 finished with value: 0.43666293842668275 and parameters: {'n_estimators': 418, 'max_depth': 3, 'learning_rate': 0.0870261443952686, 'subsample': 0.6874691660256873, 'colsample_bytree': 0.7661241073535074, 'min_child_weight': 5, 'gamma': 1.1257595342225608}. Best is trial 8 with value: 0.43776677479938536.
[I 2026-04-19 23:32:30,432] Trial 16 finished with value: 0.4374601590864998 and parameters: {'n_estimators': 252, 'max_depth': 5, 'learning_rate': 0.05360489953512494, 'subsample': 0.9940979242359855, 'colsample_bytree': 0.6010529742184962, 'min_child_weight': 2, 'gamma': 2.6536427108596587}. Best is trial 8 with value: 0.43776677479938536.
[I 2026-04-19 23:32:44,522] Trial 17 finished with value: 0.43545852027548365 and parameters: {'n_estimators': 321, 'max_depth': 5, 'learning_rate': 0.053607320877584706, 'subsample': 0.9861276993852887, 'colsample_bytree': 0.6266407704963086, 'min_child_weight': 1, 'gamma': 3.2773186511539842}. Best is trial 8 with value: 0.43776677479938536.
[I 2026-04-19 23:33:09,180] Trial 18 finished with value: 0.43623580937013773 and parameters: {'n_estimators': 545, 'max_depth': 5, 'learning_rate': 0.03968950926394598, 'subsample': 0.6838750817302159, 'colsample_bytree': 0.7686991597341626, 'min_child_weight': 2, 'gamma': 3.618761917547836}. Best is trial 8 with value: 0.43776677479938536.
[I 2026-04-19 23:33:23,921] Trial 19 finished with value: 0.4369387636869243 and parameters: {'n_estimators': 437, 'max_depth': 4, 'learning_rate': 0.07980257676026103, 'subsample': 0.9209680451993397, 'colsample_bytree': 0.621309056329615, 'min_child_weight': 6, 'gamma': 2.6324082382028027}. Best is trial 8 with value: 0.43776677479938536.
[I 2026-04-19 23:33:37,410] Trial 20 finished with value: 0.4357015742642026 and parameters: {'n_estimators': 262, 'max_depth': 6, 'learning_rate': 0.038575900793644605, 'subsample': 0.9998334506027458, 'colsample_bytree': 0.718040990389384, 'min_child_weight': 3, 'gamma': 2.1846233049286177}. Best is trial 8 with value: 0.43776677479938536.
[I 2026-04-19 23:33:47,244] Trial 21 finished with value: 0.4369455269049001 and parameters: {'n_estimators': 255, 'max_depth': 3, 'learning_rate': 0.10317230479106296, 'subsample': 0.8231229736242832, 'colsample_bytree': 0.9972593790127614, 'min_child_weight': 3, 'gamma': 2.0066115292529423}. Best is trial 8 with value: 0.43776677479938536.
[I 2026-04-19 23:33:54,280] Trial 22 finished with value: 0.4356069232521066 and parameters: {'n_estimators': 203, 'max_depth': 4, 'learning_rate': 0.10818003830161661, 'subsample': 0.9280106874214962, 'colsample_bytree': 0.943810522739879, 'min_child_weight': 4, 'gamma': 1.0266304324669757}. Best is trial 8 with value: 0.43776677479938536.
[I 2026-04-19 23:34:05,495] Trial 23 finished with value: 0.4360304989418143 and parameters: {'n_estimators': 319, 'max_depth': 3, 'learning_rate': 0.1325810051934322, 'subsample': 0.8633698142836685, 'colsample_bytree': 0.8840912285511293, 'min_child_weight': 2, 'gamma': 2.6698375791895677}. Best is trial 8 with value: 0.43776677479938536.
[I 2026-04-19 23:34:17,112] Trial 24 finished with value: 0.4357881560516198 and parameters: {'n_estimators': 254, 'max_depth': 5, 'learning_rate': 0.15161469509192027, 'subsample': 0.7873846200474118, 'colsample_bytree': 0.9500065307078225, 'min_child_weight': 3, 'gamma': 1.2457255980921158}. Best is trial 8 with value: 0.43776677479938536.
[I 2026-04-19 23:34:28,760] Trial 25 finished with value: 0.43472956486376574 and parameters: {'n_estimators': 397, 'max_depth': 3, 'learning_rate': 0.17593469870101547, 'subsample': 0.8980952967658927, 'colsample_bytree': 0.6633878214333633, 'min_child_weight': 1, 'gamma': 2.973043306195567}. Best is trial 8 with value: 0.43776677479938536.
[I 2026-04-19 23:34:41,771] Trial 26 finished with value: 0.4365781710914454 and parameters: {'n_estimators': 342, 'max_depth': 4, 'learning_rate': 0.06896007178532998, 'subsample': 0.9565926078315966, 'colsample_bytree': 0.7907865016430394, 'min_child_weight': 5, 'gamma': 3.9404428793540234}. Best is trial 8 with value: 0.43776677479938536.
[I 2026-04-19 23:34:54,551] Trial 27 finished with value: 0.43495260663507107 and parameters: {'n_estimators': 242, 'max_depth': 7, 'learning_rate': 0.09850071106914757, 'subsample': 0.6714421452350751, 'colsample_bytree': 0.8755998595996041, 'min_child_weight': 2, 'gamma': 2.0582061310502304}. Best is trial 8 with value: 0.43776677479938536.
[I 2026-04-19 23:35:05,654] Trial 28 finished with value: 0.43648189719679964 and parameters: {'n_estimators': 302, 'max_depth': 3, 'learning_rate': 0.1201997020456752, 'subsample': 0.842714466399539, 'colsample_bytree': 0.9216124732644759, 'min_child_weight': 4, 'gamma': 1.8035405417567807}. Best is trial 8 with value: 0.43776677479938536.
[I 2026-04-19 23:35:21,285] Trial 29 finished with value: 0.43512857268232746 and parameters: {'n_estimators': 379, 'max_depth': 6, 'learning_rate': 0.07089850173907386, 'subsample': 0.7549868110993019, 'colsample_bytree': 0.9781189206682775, 'min_child_weight': 6, 'gamma': 3.0158366666121226}. Best is trial 8 with value: 0.43776677479938536.

Best params: {'n_estimators': 310, 'max_depth': 3, 'learning_rate': 0.10544802842427721, 'subsample': 0.6697850190170869, 'colsample_bytree': 0.9099241063557251, 'min_child_weight': 4, 'gamma': 1.39217260181068}
Best F1: 0.43776677479938536

In [15]:
best_params = study.best_params

model = XGBClassifier(**best_params)
model.fit(X_train_res, y_train_res)

y_prob = model.predict_proba(X_test)[:, 1]
y_pred = (y_prob >= 0.5).astype(int)

In [16]:
from sklearn.metrics import classification_report, f1_score, recall_score

print(classification_report(y_test, y_pred))

print("Class 1 F1:", f1_score(y_test, y_pred, pos_label=1))
print("Class 1 Recall:", recall_score(y_test, y_pred, pos_label=1))

              precision    recall  f1-score   support

         0.0       0.85      0.97      0.90     62201
         1.0       0.51      0.15      0.24     12850

    accuracy                           0.83     75051
   macro avg       0.68      0.56      0.57     75051
weighted avg       0.79      0.83      0.79     75051

Class 1 F1: 0.2362063823441694
Class 1 Recall: 0.15408560311284047